name: WSAUpdateChecker

on:
  workflow_dispatch:
    
  schedule:
    - cron: '* * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 🏭
        uses: actions/setup-python@v4
        with:
          check-latest: true
          allow-prereleases: true
          python-version: '3.x'

      - name: Install Ubuntu Dependencies 🧑‍🏭
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: e2fsprogs attr unzip qemu-utils python3-venv
          version: 1.0

      - name: Install Python dependencies
        run: 
          pip install requests

      - name: Set up Git
        run: |
          git config --global user.email "917749218@qq.com"
          git config --global user.name "bubbles-wow"

      - name: Check update
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          HOST_SERVER: ${{ secrets.HOST_SERVER }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        run: |
          git clone https://${{ secrets.PAT }}@github.com/bubbles-wow/WSA-Archive.git WSA-Archive
          python3 WSAUpdateChecker_workflow.py
