name: WSAUpdateChecker

on:
  workflow_dispatch:
    
  schedule:
    - cron: '* * * * *'

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 🏭
        uses: actions/setup-python@v4
        with:
          check-latest: true
          python-version: '3.x'

      - name: Install Python dependencies 📦
        run: 
          pip install requests

      - name: Check Update 📡
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          HOST_SERVER: ${{ secrets.HOST_SERVER }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        run: |
          git config --global user.email '917749218@qq.com'
          git config --global user.name 'bubbles-wow'
          git clone https://${{ secrets.PAT }}@github.com/bubbles-wow/WSA-Archive.git WSA-Archive
          python3 WSAUpdateChecker_workflow.py